/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0052ae',
        'primary-container': '#006adc',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#acc7ff',
        secondary: '#48607e',
        'secondary-container': '#c3dcff',
        'secondary-fixed': '#d2e4ff',
        'secondary-fixed-dim': '#b0c8eb',
        tertiary: '#933900',
        'tertiary-container': '#ba4b01',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        background: '#f9f9ff',
        'on-background': '#191c22',
        surface: '#f9f9ff',
        'on-surface': '#191c22',
        'surface-variant': '#e1e2ec',
        'on-surface-variant': '#414753',
        'surface-container': '#ecedf7',
        'surface-container-low': '#f2f3fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8f2',
        'surface-container-highest': '#e1e2ec',
        'surface-dim': '#d8d9e3',
        'surface-bright': '#f9f9ff',
        'surface-tint': '#005bbf',
        outline: '#727785',
        'outline-variant': '#c1c6d6',
        'inverse-surface': '#2d3038',
        'inverse-on-surface': '#eff0fa',
        'inverse-primary': '#acc7ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#edf1ff',
        'on-primary-fixed': '#001a40',
        'on-primary-fixed-variant': '#004492',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#49617f',
        'on-secondary-fixed': '#001c37',
        'on-secondary-fixed-variant': '#304865',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffeee7',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7b2f00',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      // Dark mode colors
      'dark-surface': '#1e1e1e',
      'dark-surface-container': '#252525',
      'dark-surface-container-low': '#2a2a2a',
      'dark-surface-container-lowest': '#1a1a1a',
      'dark-surface-container-high': '#333333',
      'dark-on-surface': '#e0e0e0',
      'dark-on-surface-variant': '#b0b0b0',
      'dark-surface-container-highest': '#3d3d3d',
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px'
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
