/**
 * Pre-built Professional Themes with Light/Dark Variants
 * All themes are WCAG AA compliant for accessibility
 */

const themes = {
  default_blue: {
    name: 'Default Blue',
    description: 'Professional medical blue theme',
    light: {
      primary: '#0066CC',
      primaryContainer: '#D1E4FF',
      onPrimary: '#FFFFFF',
      secondary: '#535F70',
      secondaryContainer: '#D7E3F7',
      onSecondary: '#FFFFFF',
      surface: '#FEF7FF',
      surfaceContainer: '#F3F3F3',
      onSurface: '#1B1B1F',
      onSurfaceVariant: '#44474F',
      outline: '#74777F',
      background: '#FFFFFF',
      onBackground: '#1B1B1F',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
    },
    dark: {
      primary: '#9ECAFF',
      primaryContainer: '#00497D',
      onPrimary: '#003258',
      secondary: '#BBC7DB',
      secondaryContainer: '#384355',
      onSecondary: '#253042',
      surface: '#1B1B1F',
      surfaceContainer: '#212024',
      onSurface: '#E4E2E6',
      onSurfaceVariant: '#C4C6CF',
      outline: '#8E9199',
      background: '#1B1B1F',
      onBackground: '#E4E2E6',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
    },
  },
  medical_teal: {
    name: 'Medical Teal',
    description: 'Calming teal healthcare theme',
    light: {
      primary: '#006A6A',
      primaryContainer: '#74F7F7',
      onPrimary: '#FFFFFF',
      secondary: '#4A6363',
      secondaryContainer: '#CCE8E7',
      onSecondary: '#FFFFFF',
      surface: '#FAFDFC',
      surfaceContainer: '#F4F4F4',
      onSurface: '#191C1C',
      onSurfaceVariant: '#3F4949',
      outline: '#6F7979',
      background: '#FAFDFC',
      onBackground: '#191C1C',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
    },
    dark: {
      primary: '#5CDADB',
      primaryContainer: '#004F4F',
      onPrimary: '#003737',
      secondary: '#B0CCCB',
      secondaryContainer: '#324B4B',
      onSecondary: '#1F3535',
      surface: '#191C1C',
      surfaceContainer: '#202525',
      onSurface: '#E0E3E2',
      onSurfaceVariant: '#B4B8B8',
      outline: '#7E8383',
      background: '#191C1C',
      onBackground: '#E0E3E2',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
    },
  },
  professional_purple: {
    name: 'Professional Purple',
    description: 'Trustworthy purple theme',
    light: {
      primary: '#6750A4',
      primaryContainer: '#EADDFF',
      onPrimary: '#FFFFFF',
      secondary: '#625B71',
      secondaryContainer: '#E8DEF8',
      onSecondary: '#FFFFFF',
      surface: '#FEF7FF',
      surfaceContainer: '#F3F3F3',
      onSurface: '#1D1B20',
      onSurfaceVariant: '#49454F',
      outline: '#79747E',
      background: '#FEF7FF',
      onBackground: '#1D1B20',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
    },
    dark: {
      primary: '#D0BCFF',
      primaryContainer: '#4F378B',
      onPrimary: '#381E72',
      secondary: '#CCC2DC',
      secondaryContainer: '#4A4458',
      onSecondary: '#332D41',
      surface: '#1D1B20',
      surfaceContainer: '#212025',
      onSurface: '#E6E1E5',
      onSurfaceVariant: '#CAC4D0',
      outline: '#938F99',
      background: '#1D1B20',
      onBackground: '#E6E1E5',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
    },
  },
  nature_green: {
    name: 'Nature Green',
    description: 'Healing green wellness theme',
    light: {
      primary: '#2E7D32',
      primaryContainer: '#B9F6CA',
      onPrimary: '#FFFFFF',
      secondary: '#546E7A',
      secondaryContainer: '#DCE4E8',
      onSecondary: '#FFFFFF',
      surface: '#F5FBF5',
      surfaceContainer: '#F1F1F1',
      onSurface: '#1B1B1F',
      onSurfaceVariant: '#42474E',
      outline: '#72777F',
      background: '#F5FBF5',
      onBackground: '#1B1B1F',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
    },
    dark: {
      primary: '#81C784',
      primaryContainer: '#1B5E20',
      onPrimary: '#003300',
      secondary: '#B0BEC5',
      secondaryContainer: '#37474F',
      onSecondary: '#263238',
      surface: '#1B1B1F',
      surfaceContainer: '#212421',
      onSurface: '#E4E3E5',
      onSurfaceVariant: '#C4C8C9',
      outline: '#8E9293',
      background: '#1B1B1F',
      onBackground: '#E4E3E5',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
    },
  },
  warm_orange: {
    name: 'Warm Orange',
    description: 'Friendly approachable theme',
    light: {
      primary: '#E65100',
      primaryContainer: '#FFCCBC',
      onPrimary: '#FFFFFF',
      secondary: '#5D4037',
      secondaryContainer: '#D7CCC8',
      onSecondary: '#FFFFFF',
      surface: '#FFF8F5',
      surfaceContainer: '#F3F3F3',
      onSurface: '#1B1B1F',
      onSurfaceVariant: '#474747',
      outline: '#777777',
      background: '#FFF8F5',
      onBackground: '#1B1B1F',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
    },
    dark: {
      primary: '#FFAB91',
      primaryContainer: '#BF360C',
      onPrimary: '#7F2200',
      secondary: '#BCAAA4',
      secondaryContainer: '#5D4037',
      onSecondary: '#3E2723',
      surface: '#1B1B1F',
      surfaceContainer: '#262220',
      onSurface: '#E6E2E0',
      onSurfaceVariant: '#C9C6C4',
      outline: '#938F8E',
      background: '#1B1B1F',
      onBackground: '#E6E2E0',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
    },
  },
  modern_gray: {
    name: 'Modern Gray',
    description: 'Minimalist clean theme',
    light: {
      primary: '#424242',
      primaryContainer: '#E0E0E0',
      onPrimary: '#FFFFFF',
      secondary: '#616161',
      secondaryContainer: '#E8E8E8',
      onSecondary: '#FFFFFF',
      surface: '#FAFAFA',
      surfaceContainer: '#F5F5F5',
      onSurface: '#1B1B1F',
      onSurfaceVariant: '#424242',
      outline: '#757575',
      background: '#FAFAFA',
      onBackground: '#1B1B1F',
      error: '#BA1A1A',
      onError: '#FFFFFF',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
    },
    dark: {
      primary: '#B0B0B0',
      primaryContainer: '#2C2C2C',
      onPrimary: '#1A1A1A',
      secondary: '#9E9E9E',
      secondaryContainer: '#424242',
      onSecondary: '#2C2C2C',
      surface: '#1B1B1F',
      surfaceContainer: '#2C2C2C',
      onSurface: '#E0E0E0',
      onSurfaceVariant: '#B0B0B0',
      outline: '#757575',
      background: '#1B1B1F',
      onBackground: '#E0E0E0',
      error: '#FFB4AB',
      onError: '#690005',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
    },
  },
};

/**
 * Get theme by ID
 */
const getTheme = (themeId) => {
  return themes[themeId] || themes.default_blue;
};

/**
 * Get all themes
 */
const getAllThemes = () => {
  return Object.entries(themes).map(([id, theme]) => ({
    id,
    ...theme,
  }));
};

/**
 * Get theme colors for a specific mode
 */
const getThemeColors = (themeId, mode = 'light') => {
  const theme = getTheme(themeId);
  return theme[mode] || theme.light;
};

module.exports = {
  themes,
  getTheme,
  getAllThemes,
  getThemeColors,
};
